-- world-drawer schema (Postgres only, v9相当の最終形)
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS pixels(
  x INTEGER NOT NULL, y INTEGER NOT NULL,
  c TEXT NOT NULL, t TEXT NOT NULL DEFAULT 'normal', by TEXT,
  coats INTEGER NOT NULL DEFAULT 1,
  shieldUntil DOUBLE PRECISION NOT NULL DEFAULT 0,
  chalkUntil DOUBLE PRECISION NOT NULL DEFAULT 0,
  PRIMARY KEY (x, y));
CREATE INDEX IF NOT EXISTS idx_pixels_box
  ON pixels(x, y, c, t, by, coats, shieldUntil, chalkUntil);
CREATE INDEX IF NOT EXISTS idx_pixels_by ON pixels(by);
CREATE TABLE IF NOT EXISTS users(
  token TEXT PRIMARY KEY, uid TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL, color TEXT NOT NULL,
  inventory TEXT NOT NULL DEFAULT '{}',
  cooldownUntil DOUBLE PRECISION NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 1, xp INTEGER NOT NULL DEFAULT 0,
  transferCode TEXT UNIQUE, passwordHash TEXT, country TEXT,
  showCountry INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS history(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  x INTEGER NOT NULL, y INTEGER NOT NULL,
  uid TEXT NOT NULL, c TEXT NOT NULL, t TEXT NOT NULL,
  at DOUBLE PRECISION NOT NULL, undone INTEGER NOT NULL DEFAULT 0,
  xp INTEGER NOT NULL DEFAULT 0, rewardInk TEXT,
  rewardAmount INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_history_cell ON history(x, y, at);
CREATE INDEX IF NOT EXISTS idx_history_uid ON history(uid);
