-- 005: お知らせテーブル。新しい順に取得するためid降順で読む。
CREATE TABLE IF NOT EXISTS notices(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  createdAt DOUBLE PRECISION NOT NULL,
  updatedAt DOUBLE PRECISION NOT NULL);
